### ISSUE TITLE
Object.extname is deprecated.

### ISSUE THREAD

**Issue by ghost** [Roobyx/Autocompiler-Pug-Jade#4]
Argument to `path.extname` must be a string
```
Object.extname (/Applications/Atom.app/Contents/Resources/app.asar/src/electron-shims.js:20:10)
Object.toggle (/Users/demidborodin/.atom/packages/autocompiler-pug-jade/lib/autocompiler-pug-jade.js:213:28)
<unknown> (/Users/demidborodin/.atom/packages/autocompiler-pug-jade/lib/autocompiler-pug-jade.js:80:15)
Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:129:28)
<unknown> (/Applications/Atom.app/Contents/Resources/app.asar/src/pane-container.js:348:27)
```

**Comment by JohnMica** [comment]
Argument to path.extname must be a string
Report Issue
Object.extname - /Applications/Atom.app/Contents/Resources/app/src/electron-shims.js:20:10
Object.toggle - /Users/johnmica/.atom/packages/autocompiler-pug-jade/lib/autocompiler-pug-jade.js:213:28
<unknown> - /Users/johnmica/.atom/packages/autocompiler-pug-jade/lib/autocompiler-pug-jade.js:80:15
Function.module.exports.Emitter.simpleDispatch - <embedded>:63490:20
Emitter.emit - <embedded>:63606:34
Workspace.didChangeActivePaneItemOnPaneContainer - <embedded>:26104:28


just after the latest udpateof Atom

**Comment by hugecat** [comment]
Argument to path.extname must be a string

Object.extname - /Applications/Atom.app/Contents/Resources/app.asar/src/electron-shims.js:20:10
Object.toggle - /Users/hugecat/.atom/packages/autocompiler-pug-jade/lib/autocompiler-pug-jade.js:213:28
<unknown> - /Users/hugecat/.atom/packages/autocompiler-pug-jade/lib/autocompiler-pug-jade.js:80:15
Function.module.exports.Emitter.simpleDispatch - <embedded>:68080:20
Emitter.emit - <embedded>:68209:34
Workspace.didChangeActivePaneItemOnPaneContainer - <embedded>:28522:26
